# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/telemetry/conventions.proto

require 'google/protobuf'

require 'routeiq/v1/telemetry/entities_pb'


descriptor_data = "\n&routeiq/v1/telemetry/conventions.proto\x12\x14routeiq.v1.telemetry\x1a#routeiq/v1/telemetry/entities.proto\"\xc1\x01\n\x12SemanticConvention\x12(\n\x10proto_field_path\x18\x01 \x01(\tR\x0eprotoFieldPath\x12,\n\x12otel_attribute_key\x18\x02 \x01(\tR\x10otelAttributeKey\x12\x37\n\x04type\x18\x03 \x01(\x0e\x32#.routeiq.v1.telemetry.AttributeTypeR\x04type\x12\x1a\n\x08required\x18\x04 \x01(\x08R\x08required\"`\n\x12\x43onventionRegistry\x12J\n\x0b\x63onventions\x18\x01 \x03(\x0b\x32(.routeiq.v1.telemetry.SemanticConventionR\x0b\x63onventionsB\x9c\x01\n2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\x10\x43onventionsProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Telemetry
      SemanticConvention = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.SemanticConvention").msgclass
      ConventionRegistry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.ConventionRegistry").msgclass
    end
  end
end
