# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/telemetry/entities.proto

require 'google/protobuf'


descriptor_data = "\n#routeiq/v1/telemetry/entities.proto\x12\x14routeiq.v1.telemetry*x\n\x10\x43ompletionStatus\x12!\n\x1d\x43OMPLETION_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x0b\n\x07PARTIAL\x10\x03\x12\r\n\tCANCELLED\x10\x04\x12\x0b\n\x07TIMEOUT\x10\x05*\xd2\x01\n\x0f\x46\x61ilureCategory\x12 \n\x1c\x46\x41ILURE_CATEGORY_UNSPECIFIED\x10\x00\x12\x0e\n\nTOOL_ERROR\x10\x01\x12\x0f\n\x0bMODEL_ERROR\x10\x02\x12\x10\n\x0cPOLICY_BLOCK\x10\x03\x12\x11\n\rLOOP_DETECTED\x10\x04\x12\x14\n\x10TIMEOUT_EXCEEDED\x10\x05\x12\x13\n\x0fHUMAN_CANCELLED\x10\x06\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x07\x12\x14\n\x10\x43ONTEXT_OVERFLOW\x10\x08*b\n\x0c\x41utonomyMode\x12\x1d\n\x19\x41UTONOMY_MODE_UNSPECIFIED\x10\x00\x12\x0e\n\nSUPERVISED\x10\x01\x12\x13\n\x0fSEMI_AUTONOMOUS\x10\x02\x12\x0e\n\nAUTONOMOUS\x10\x03*R\n\x08RiskTier\x12\x19\n\x15RISK_TIER_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04*n\n\x0fPermissionLevel\x12 \n\x1cPERMISSION_LEVEL_UNSPECIFIED\x10\x00\x12\r\n\tREAD_ONLY\x10\x01\x12\x0e\n\nREAD_WRITE\x10\x02\x12\x0e\n\nPRIVILEGED\x10\x03\x12\n\n\x06SYSTEM\x10\x04*\x88\x01\n\x10ToolResultStatus\x12\"\n\x1eTOOL_RESULT_STATUS_UNSPECIFIED\x10\x00\x12\x10\n\x0cTOOL_SUCCESS\x10\x01\x12\x10\n\x0cTOOL_FAILURE\x10\x02\x12\x10\n\x0cTOOL_TIMEOUT\x10\x03\x12\x1a\n\x16TOOL_PERMISSION_DENIED\x10\x04*y\n\rAttributeType\x12\x1e\n\x1a\x41TTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06STRING\x10\x01\x12\t\n\x05INT64\x10\x02\x12\n\n\x06\x44OUBLE\x10\x03\x12\x08\n\x04\x42OOL\x10\x04\x12\t\n\x05\x42YTES\x10\x05\x12\x10\n\x0cSTRING_ARRAY\x10\x06\x42\x99\x01\n2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\rEntitiesProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Telemetry
      CompletionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.CompletionStatus").enummodule
      FailureCategory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.FailureCategory").enummodule
      AutonomyMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.AutonomyMode").enummodule
      RiskTier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.RiskTier").enummodule
      PermissionLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.PermissionLevel").enummodule
      ToolResultStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.ToolResultStatus").enummodule
      AttributeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.telemetry.AttributeType").enummodule
    end
  end
end
