# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/admin/billing.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'routeiq/v1/admin/organization_pb'


descriptor_data = "\n\x1erouteiq/v1/admin/billing.proto\x12\x10routeiq.v1.admin\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/admin/organization.proto\"\xdf\x02\n\x0cUsageSummary\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12=\n\x0cperiod_start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bperiodStart\x12\x39\n\nperiod_end\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tperiodEnd\x12\'\n\x0f\x65vents_ingested\x18\x04 \x01(\x03R\x0e\x65ventsIngested\x12+\n\x11metrics_evaluated\x18\x05 \x01(\x03R\x10metricsEvaluated\x12\x30\n\x14\x66rontier_judge_calls\x18\x06 \x01(\x03R\x12\x66rontierJudgeCalls\x12$\n\x0etotal_cost_usd\x18\x07 \x01(\x01R\x0ctotalCostUsd\"\xe6\x01\n\x05Quota\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12*\n\x04tier\x18\x02 \x01(\x0e\x32\x16.routeiq.v1.admin.TierR\x04tier\x12(\n\x10\x65vents_per_month\x18\x03 \x01(\x03R\x0e\x65ventsPerMonth\x12\x37\n\x18\x66rontier_calls_per_month\x18\x04 \x01(\x03R\x15\x66rontierCallsPerMonth\x12%\n\x0eretention_days\x18\x05 \x01(\x03R\rretentionDays\"\xb4\x01\n\x0fGetUsageRequest\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12=\n\x0cperiod_start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bperiodStart\x12\x39\n\nperiod_end\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tperiodEnd\":\n\x0fGetQuotaRequest\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId2\xa7\x01\n\x0e\x42illingService\x12M\n\x08GetUsage\x12!.routeiq.v1.admin.GetUsageRequest\x1a\x1e.routeiq.v1.admin.UsageSummary\x12\x46\n\x08GetQuota\x12!.routeiq.v1.admin.GetQuotaRequest\x1a\x17.routeiq.v1.admin.QuotaB\x8c\x01\n.build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\x0c\x42illingProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Admin
      UsageSummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.UsageSummary").msgclass
      Quota = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.Quota").msgclass
      GetUsageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.GetUsageRequest").msgclass
      GetQuotaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.GetQuotaRequest").msgclass
    end
  end
end
