# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/admin/slo_config.proto

require 'google/protobuf'


descriptor_data = "\n!routeiq/v1/admin/slo_config.proto\x12\x10routeiq.v1.admin\"\x8e\x01\n\x0bSloOverride\x12\x1b\n\tmetric_id\x18\x01 \x01(\tR\x08metricId\x12!\n\x0cworkspace_id\x18\x02 \x01(\tR\x0bworkspaceId\x12\x12\n\x04tier\x18\x03 \x01(\tR\x04tier\x12+\n\x11target_expression\x18\x04 \x01(\tR\x10targetExpression\"n\n\x0cSloOverrides\x12!\n\x0cworkspace_id\x18\x01 \x01(\tR\x0bworkspaceId\x12;\n\toverrides\x18\x02 \x03(\x0b\x32\x1d.routeiq.v1.admin.SloOverrideR\toverrides\";\n\x16GetSloOverridesRequest\x12!\n\x0cworkspace_id\x18\x01 \x01(\tR\x0bworkspaceId\"R\n\x15SetSloOverrideRequest\x12\x39\n\x08override\x18\x01 \x01(\x0b\x32\x1d.routeiq.v1.admin.SloOverrideR\x08override\"n\n\x18\x44\x65leteSloOverrideRequest\x12\x1b\n\tmetric_id\x18\x01 \x01(\tR\x08metricId\x12!\n\x0cworkspace_id\x18\x02 \x01(\tR\x0bworkspaceId\x12\x12\n\x04tier\x18\x03 \x01(\tR\x04tier2\xaa\x02\n\x10SloConfigService\x12[\n\x0fGetSloOverrides\x12(.routeiq.v1.admin.GetSloOverridesRequest\x1a\x1e.routeiq.v1.admin.SloOverrides\x12X\n\x0eSetSloOverride\x12\'.routeiq.v1.admin.SetSloOverrideRequest\x1a\x1d.routeiq.v1.admin.SloOverride\x12_\n\x11\x44\x65leteSloOverride\x12*.routeiq.v1.admin.DeleteSloOverrideRequest\x1a\x1e.routeiq.v1.admin.SloOverridesB\x8e\x01\n.build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\x0eSloConfigProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Admin
      SloOverride = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.SloOverride").msgclass
      SloOverrides = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.SloOverrides").msgclass
      GetSloOverridesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.GetSloOverridesRequest").msgclass
      SetSloOverrideRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.SetSloOverrideRequest").msgclass
      DeleteSloOverrideRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.admin.DeleteSloOverrideRequest").msgclass
    end
  end
end
