# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/control/escalation.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n#routeiq/v1/control/escalation.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n\x0f\x45scalateRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n\x06reason\x18\x02 \x01(\tR\x06reason\x12\'\n\x0f\x63ontext_summary\x18\x03 \x01(\tR\x0e\x63ontextSummary\x12?\n\x07urgency\x18\x04 \x01(\x0e\x32%.routeiq.v1.control.EscalationUrgencyR\x07urgency\"\xad\x01\n\x10\x45scalateResponse\x12#\n\rescalation_id\x18\x01 \x01(\tR\x0c\x65scalationId\x12\x39\n\x05state\x18\x02 \x01(\x0e\x32#.routeiq.v1.control.EscalationStateR\x05state\x12\x39\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n\x18ResolveEscalationRequest\x12#\n\rescalation_id\x18\x01 \x01(\tR\x0c\x65scalationId\x12\x1e\n\nresolution\x18\x02 \x01(\tR\nresolution\x12\x1a\n\x08\x61pproved\x18\x03 \x01(\x08R\x08\x61pproved\"7\n\x19ResolveEscalationResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted*d\n\x11\x45scalationUrgency\x12\"\n\x1e\x45SCALATION_URGENCY_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04*l\n\x0f\x45scalationState\x12 \n\x1c\x45SCALATION_STATE_UNSPECIFIED\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\x10\n\x0c\x41\x43KNOWLEDGED\x10\x02\x12\x0c\n\x08RESOLVED\x10\x03\x12\r\n\tTIMED_OUT\x10\x04\x32\xdc\x01\n\x11\x45scalationService\x12U\n\x08\x45scalate\x12#.routeiq.v1.control.EscalateRequest\x1a$.routeiq.v1.control.EscalateResponse\x12p\n\x11ResolveEscalation\x12,.routeiq.v1.control.ResolveEscalationRequest\x1a-.routeiq.v1.control.ResolveEscalationResponseB\x95\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0f\x45scalationProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Control
      EscalateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.EscalateRequest").msgclass
      EscalateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.EscalateResponse").msgclass
      ResolveEscalationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.ResolveEscalationRequest").msgclass
      ResolveEscalationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.ResolveEscalationResponse").msgclass
      EscalationUrgency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.EscalationUrgency").enummodule
      EscalationState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.EscalationState").enummodule
    end
  end
end
