# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/control/guardrail.proto

require 'google/protobuf'

require 'routeiq/v1/telemetry/entities_pb'


descriptor_data = "\n\"routeiq/v1/control/guardrail.proto\x12\x12routeiq.v1.control\x1a#routeiq/v1/telemetry/entities.proto\"\xd4\x01\n\x15\x43heckGuardrailRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\'\n\x0fproposed_action\x18\x02 \x01(\tR\x0eproposedAction\x12P\n\x10permission_level\x18\x03 \x01(\x0e\x32%.routeiq.v1.telemetry.PermissionLevelR\x0fpermissionLevel\x12!\n\x0crisk_context\x18\x04 \x01(\tR\x0briskContext\"\xa2\x01\n\x16\x43heckGuardrailResponse\x12>\n\x07verdict\x18\x01 \x01(\x0e\x32$.routeiq.v1.control.GuardrailVerdictR\x07verdict\x12\x16\n\x06reason\x18\x02 \x01(\tR\x06reason\x12\x30\n\x14policy_ids_triggered\x18\x03 \x03(\tR\x12policyIdsTriggered\"\x82\x01\n\x15RegisterPolicyRequest\x12\x1b\n\tpolicy_id\x18\x01 \x01(\tR\x08policyId\x12%\n\x0e\x62undle_version\x18\x02 \x01(\tR\rbundleVersion\x12%\n\x0epolicy_content\x18\x03 \x01(\x0cR\rpolicyContent\"a\n\x16RegisterPolicyResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted\x12+\n\x11\x65\x66\x66\x65\x63tive_version\x18\x02 \x01(\tR\x10\x65\x66\x66\x65\x63tiveVersion*a\n\x10GuardrailVerdict\x12!\n\x1dGUARDRAIL_VERDICT_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\t\n\x05\x42LOCK\x10\x02\x12\x14\n\x10REQUIRE_APPROVAL\x10\x03\x32\xe4\x01\n\x10GuardrailService\x12g\n\x0e\x43heckGuardrail\x12).routeiq.v1.control.CheckGuardrailRequest\x1a*.routeiq.v1.control.CheckGuardrailResponse\x12g\n\x0eRegisterPolicy\x12).routeiq.v1.control.RegisterPolicyRequest\x1a*.routeiq.v1.control.RegisterPolicyResponseB\x94\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0eGuardrailProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Control
      CheckGuardrailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.CheckGuardrailRequest").msgclass
      CheckGuardrailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.CheckGuardrailResponse").msgclass
      RegisterPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.RegisterPolicyRequest").msgclass
      RegisterPolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.RegisterPolicyResponse").msgclass
      GuardrailVerdict = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.GuardrailVerdict").enummodule
    end
  end
end
