# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/control/intervention.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'routeiq/v1/telemetry/entities_pb'


descriptor_data = "\n%routeiq/v1/control/intervention.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/telemetry/entities.proto\"\xd4\x01\n\x1aTriggerInterventionRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x38\n\x04kind\x18\x02 \x01(\x0e\x32$.routeiq.v1.control.InterventionKindR\x04kind\x12\x16\n\x06reason\x18\x03 \x01(\tR\x06reason\x12\x45\n\x0c\x64owngrade_to\x18\x04 \x01(\x0e\x32\".routeiq.v1.telemetry.AutonomyModeR\x0b\x64owngradeTo\"\x9b\x01\n\x1bTriggerInterventionResponse\x12\'\n\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12\x18\n\x07\x61pplied\x18\x02 \x01(\x08R\x07\x61pplied\x12\x39\n\napplied_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tappliedAt\"G\n\x1cGetInterventionStatusRequest\x12\'\n\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\"\x9a\x01\n\x1dGetInterventionStatusResponse\x12\'\n\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12\x38\n\x04kind\x18\x02 \x01(\x0e\x32$.routeiq.v1.control.InterventionKindR\x04kind\x12\x16\n\x06\x61\x63tive\x18\x03 \x01(\x08R\x06\x61\x63tive*\x8d\x01\n\x10InterventionKind\x12!\n\x1dINTERVENTION_KIND_UNSPECIFIED\x10\x00\x12\x11\n\rCIRCUIT_BREAK\x10\x01\x12\x0c\n\x08ROLLBACK\x10\x02\x12\x16\n\x12\x41UTONOMY_DOWNGRADE\x10\x03\x12\x0e\n\nMODEL_SWAP\x10\x04\x12\r\n\tHARD_STOP\x10\x05\x32\x8b\x02\n\x13InterventionService\x12v\n\x13TriggerIntervention\x12..routeiq.v1.control.TriggerInterventionRequest\x1a/.routeiq.v1.control.TriggerInterventionResponse\x12|\n\x15GetInterventionStatus\x12\x30.routeiq.v1.control.GetInterventionStatusRequest\x1a\x31.routeiq.v1.control.GetInterventionStatusResponseB\x97\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x11InterventionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Control
      TriggerInterventionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.TriggerInterventionRequest").msgclass
      TriggerInterventionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.TriggerInterventionResponse").msgclass
      GetInterventionStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.GetInterventionStatusRequest").msgclass
      GetInterventionStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.GetInterventionStatusResponse").msgclass
      InterventionKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.InterventionKind").enummodule
    end
  end
end
