# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/control/session.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'routeiq/v1/telemetry/entities_pb'


descriptor_data = "\n routeiq/v1/control/session.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/telemetry/entities.proto\"\x8e\x02\n\x13StartSessionRequest\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n\x08\x61gent_id\x18\x02 \x01(\tR\x07\x61gentId\x12\x1b\n\ttenant_id\x18\x03 \x01(\tR\x08tenantId\x12 \n\x0b\x65nvironment\x18\x04 \x01(\tR\x0b\x65nvironment\x12G\n\rautonomy_mode\x18\x05 \x01(\x0e\x32\".routeiq.v1.telemetry.AutonomyModeR\x0c\x61utonomyMode\x12;\n\trisk_tier\x18\x06 \x01(\x0e\x32\x1e.routeiq.v1.telemetry.RiskTierR\x08riskTier\"p\n\x14StartSessionResponse\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x39\n\nstarted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\"\x87\x01\n\x11\x45ndSessionRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12S\n\x11\x63ompletion_status\x18\x02 \x01(\x0e\x32&.routeiq.v1.telemetry.CompletionStatusR\x10\x63ompletionStatus\"0\n\x12\x45ndSessionResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted\"q\n\x12UpdateStateRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n\tstate_key\x18\x02 \x01(\tR\x08stateKey\x12\x1f\n\x0bstate_value\x18\x03 \x01(\x0cR\nstateValue\"V\n\x13UpdateStateResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted\x12#\n\rstate_version\x18\x02 \x01(\tR\x0cstateVersion2\xb0\x02\n\x0eSessionService\x12\x61\n\x0cStartSession\x12\'.routeiq.v1.control.StartSessionRequest\x1a(.routeiq.v1.control.StartSessionResponse\x12[\n\nEndSession\x12%.routeiq.v1.control.EndSessionRequest\x1a&.routeiq.v1.control.EndSessionResponse\x12^\n\x0bUpdateState\x12&.routeiq.v1.control.UpdateStateRequest\x1a\'.routeiq.v1.control.UpdateStateResponseB\x92\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0cSessionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Control
      StartSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.StartSessionRequest").msgclass
      StartSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.StartSessionResponse").msgclass
      EndSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.EndSessionRequest").msgclass
      EndSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.EndSessionResponse").msgclass
      UpdateStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.UpdateStateRequest").msgclass
      UpdateStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.control.UpdateStateResponse").msgclass
    end
  end
end
