# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/insights/alerts.proto

require 'google/protobuf'


descriptor_data = "\n routeiq/v1/insights/alerts.proto\x12\x13routeiq.v1.insights\"\xaf\x02\n\tAlertRule\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\tmetric_id\x18\x02 \x01(\tR\x08metricId\x12<\n\tcondition\x18\x03 \x01(\x0b\x32\x1e.routeiq.v1.insights.ConditionR\tcondition\x12\x39\n\x08severity\x18\x04 \x01(\x0e\x32\x1d.routeiq.v1.insights.SeverityR\x08severity\x12@\n\x07\x61\x63tions\x18\x05 \x03(\x0e\x32&.routeiq.v1.insights.RecommendedActionR\x07\x61\x63tions\x12 \n\x0b\x64\x65scription\x18\x06 \x01(\tR\x0b\x64\x65scription\x12\x18\n\x07\x65nabled\x18\x07 \x01(\x08R\x07\x65nabled\"\x91\x01\n\tCondition\x12-\n\x02op\x18\x01 \x01(\x0e\x32\x1d.routeiq.v1.insights.OperatorR\x02op\x12\x1c\n\tthreshold\x18\x02 \x01(\x01R\tthreshold\x12\x16\n\x06window\x18\x03 \x01(\tR\x06window\x12\x1f\n\x0bmin_samples\x18\x04 \x01(\x05R\nminSamples*l\n\x08Operator\x12\x18\n\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x06\n\x02GT\x10\x01\x12\x06\n\x02LT\x10\x02\x12\x07\n\x03GTE\x10\x03\x12\x07\n\x03LTE\x10\x04\x12\x06\n\x02\x45Q\x10\x05\x12\x0c\n\x08TREND_UP\x10\x06\x12\x0e\n\nTREND_DOWN\x10\x07*S\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\x0c\n\x08\x43RITICAL\x10\x03\x12\x08\n\x04PAGE\x10\x04*\xa5\x01\n\x11RecommendedAction\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x13\n\x0fREDUCE_AUTONOMY\x10\x01\x12\x11\n\rCIRCUIT_BREAK\x10\x02\x12\x12\n\x0e\x45SCALATE_HUMAN\x10\x03\x12\x14\n\x10ROLLBACK_VERSION\x10\x04\x12\x10\n\x0cSWITCH_MODEL\x10\x05\x12\x14\n\x10REQUIRE_APPROVAL\x10\x06\x42\x94\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x0b\x41lertsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Insights
      AlertRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.AlertRule").msgclass
      Condition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.Condition").msgclass
      Operator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.Operator").enummodule
      Severity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.Severity").enummodule
      RecommendedAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.RecommendedAction").enummodule
    end
  end
end
