# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/insights/dashboards.proto

require 'google/protobuf'


descriptor_data = "\n$routeiq/v1/insights/dashboards.proto\x12\x13routeiq.v1.insights\"\xb0\x01\n\x0f\x44\x61shboardWidget\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n\nmetric_ids\x18\x03 \x03(\tR\tmetricIds\x12\x33\n\x04type\x18\x04 \x01(\x0e\x32\x1f.routeiq.v1.insights.WidgetTypeR\x04type\x12#\n\rdefault_range\x18\x05 \x01(\tR\x0c\x64\x65\x66\x61ultRange\"q\n\tDashboard\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12>\n\x07widgets\x18\x03 \x03(\x0b\x32$.routeiq.v1.insights.DashboardWidgetR\x07widgets*k\n\nWidgetType\x12\x1b\n\x17WIDGET_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05GAUGE\x10\x01\x12\x0e\n\nTIMESERIES\x10\x02\x12\t\n\x05TABLE\x10\x03\x12\x0b\n\x07HEATMAP\x10\x04\x12\r\n\tSPARKLINE\x10\x05\x42\x98\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x0f\x44\x61shboardsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Insights
      DashboardWidget = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.DashboardWidget").msgclass
      Dashboard = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.Dashboard").msgclass
      WidgetType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.WidgetType").enummodule
    end
  end
end
