# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/insights/interventions.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'routeiq/v1/insights/alerts_pb'


descriptor_data = "\n\'routeiq/v1/insights/interventions.proto\x12\x13routeiq.v1.insights\x1a\x1fgoogle/protobuf/timestamp.proto\x1a routeiq/v1/insights/alerts.proto\"\xeb\x02\n\x1aInterventionRecommendation\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\"\n\ralert_rule_id\x18\x02 \x01(\tR\x0b\x61lertRuleId\x12\x1b\n\tmetric_id\x18\x03 \x01(\tR\x08metricId\x12>\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32&.routeiq.v1.insights.RecommendedActionR\x06\x61\x63tion\x12\x1c\n\trationale\x18\x05 \x01(\tR\trationale\x12\x1e\n\nconfidence\x18\x06 \x01(\x01R\nconfidence\x12=\n\x0cgenerated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bgeneratedAt\x12?\n\x06status\x18\x08 \x01(\x0e\x32\'.routeiq.v1.insights.InterventionStatusR\x06status*o\n\x12InterventionStatus\x12#\n\x1fINTERVENTION_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07\x41PPLIED\x10\x02\x12\r\n\tDISMISSED\x10\x03\x12\x0b\n\x07\x45XPIRED\x10\x04\x42\x9b\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x12InterventionsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Insights
      InterventionRecommendation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.InterventionRecommendation").msgclass
      InterventionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.InterventionStatus").enummodule
    end
  end
end
