# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routeiq/v1/insights/slo.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x1drouteiq/v1/insights/slo.proto\x12\x13routeiq.v1.insights\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n\tSloTarget\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\tmetric_id\x18\x02 \x01(\tR\x08metricId\x12!\n\x0cworkspace_id\x18\x03 \x01(\tR\x0bworkspaceId\x12\x12\n\x04tier\x18\x04 \x01(\tR\x04tier\x12+\n\x11target_expression\x18\x05 \x01(\tR\x10targetExpression\x12\x16\n\x06window\x18\x06 \x01(\tR\x06window\"\xb1\x02\n\tSloStatus\x12\x15\n\x06slo_id\x18\x01 \x01(\tR\x05sloId\x12\x1b\n\tmetric_id\x18\x02 \x01(\tR\x08metricId\x12#\n\rcurrent_value\x18\x03 \x01(\x01R\x0c\x63urrentValue\x12!\n\x0ctarget_value\x18\x04 \x01(\x01R\x0btargetValue\x12\x33\n\x05state\x18\x05 \x01(\x0e\x32\x1d.routeiq.v1.insights.SloStateR\x05state\x12\x34\n\x16\x65rror_budget_remaining\x18\x06 \x01(\x01R\x14\x65rrorBudgetRemaining\x12=\n\x0c\x65valuated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0b\x65valuatedAt*M\n\x08SloState\x12\x19\n\x15SLO_STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07MEETING\x10\x01\x12\x0b\n\x07\x41T_RISK\x10\x02\x12\x0c\n\x08\x42REACHED\x10\x03\x42\x91\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x08SloProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Routeiq
  module V1
    module Insights
      SloTarget = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.SloTarget").msgclass
      SloStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.SloStatus").msgclass
      SloState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("routeiq.v1.insights.SloState").enummodule
    end
  end
end
